name: push-adkg-cli-docker
on:
  push:
    branches:
      # all branches, docker image is only pushed on main
      - "*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

env:
  SERVICE_ACCOUNT: github@randamu-prod.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev/randamu-prod/candyland
  IMAGE_MAINTAINER: "Randamu"
  IMAGE_VENDOR: "Randamu"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # this might not work at all, but might work and
          # allow us to bypass dockerhub ratelimit
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
          ## this does work to avoid the dockerhub ratelimit
          driver-opts: |
            image=mirror.gcr.io/moby/buildkit:buildx-stable-1
            network=host

      - name : Add SHORT_SHA Environment Variable
        id   : short-sha
        shell: bash
        run  : echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
                ${{ steps.meta.outputs.tags }}
                ghcr.io/bbjubjub2494/dcipher/adkg-cli:main-latest
                ghcr.io/bbjubjub2494/dcipher/adkg-cli:${{ env.SHORT_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./crates/adkg-cli/Dockerfile

      - name : extract binary
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run  : |
          docker pull ghcr.io/bbjubjub2494/dcipher/adkg-cli:${{ env.SHORT_SHA }}
          container=$(docker create ghcr.io/bbjubjub2494/dcipher/adkg-cli:${{ env.SHORT_SHA }})
          docker cp $container:usr/local/bin/adkg-cli ./adkg-cli
          docker rm $container

      - name: upload binary to release
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} ./adkg-cli
